[org/gnome/desktop/interface]
cursor-theme='Yaru'
gtk-im-module='gtk-im-context-simple'
gtk-theme='Ant-Dracula'
icon-theme='Tela-dark'

[org/gnome/desktop/wm/keybindings]
activate-window-menu=@as []
begin-move=@as []
begin-resize=@as []
close=['<Super>q']
cycle-group=@as []
cycle-group-backward=@as []
cycle-panels=@as []
cycle-panels-backward=@as []
cycle-windows=@as []
cycle-windows-backward=@as []
minimize=['<Super>m']
move-to-workspace-1=@as []
move-to-workspace-down=['<Shift><Super>s']
move-to-workspace-last=@as []
move-to-workspace-up=['<Shift><Super>w']
panel-run-dialog=['<Alt>2']
show-desktop=['<Super>d']
switch-applications=@as []
switch-applications-backward=@as []
switch-group=@as []
switch-group-backward=@as []
switch-panels=@as []
switch-panels-backward=@as []
switch-to-workspace-1=@as []
switch-to-workspace-down=['<Super>s']
switch-to-workspace-last=@as []
switch-to-workspace-up=['<Super>w']
switch-windows=['<Alt>Tab']
switch-windows-backward=['<Shift><Alt>Tab']
toggle-maximized=['<Super>Up']

[org/gnome/desktop/wm/preferences]
auto-raise=true
button-layout='appmenu:maximize,close'
focus-mode='click'

[org/gnome/gedit/preferences/editor]
scheme='solarized-dark'
wrap-last-split-mode='word'

[org/gnome/gedit/preferences/ui]
show-tabs-mode='auto'

[org/gnome/mutter]
center-new-windows=true
edge-tiling=false
workspaces-only-on-primary=true

[org/gnome/mutter/keybindings]
toggle-tiled-left=['<Super>Left']
toggle-tiled-right=['<Super>Right']

[org/gnome/nautilus/preferences]
default-folder-viewer='list-view'
search-filter-time-type='last_modified'
search-view='list-view'

[org/gnome/settings-daemon/plugins/media-keys]
logout=['<Primary><Alt>n']
search=@as []

[org/gnome/shell/app-switcher]
current-workspace-only=true

[org/gnome/shell/extensions/dash-to-dock]
animate-show-apps=true
apply-custom-theme=false
custom-background-color=false
custom-theme-shrink=true
customize-alphas=true
dash-max-icon-size=32
dock-position='LEFT'
force-straight-corner=true
height-fraction=0.90000000000000002
icon-size-fixed=true
isolate-monitors=false
isolate-workspaces=true
max-alpha=0.80000000000000004
running-indicator-style='DOTS'
show-apps-at-top=false
show-trash=false
transparency-mode='DYNAMIC'

[org/gnome/shell/extensions/desktop-icons]
show-home=false
show-mount=false
show-trash=false

[org/gnome/shell/extensions/freon]
drive-utility='nvmecli'
gpu-utility='nvidia-settings'
group-temperature=true
hot-sensors=['GeForce GTX 1050 Ti', '__average__']
position-in-panel='right'
show-degrees-on-panel=true
show-fan-rpm=true
show-icon-on-panel=true

[org/gnome/shell/extensions/pop-shell]
focus-down=@as []
focus-left=@as []
focus-right=@as []
focus-up=@as []
gap-inner=uint32 1
gap-outer=uint32 1
show-title=false
tile-by-default=false
tile-move-left=['Left', 'h']
toggle-stacking-global=@as []

[org/gnome/shell/extensions/unite]
app-menu-ellipsize-mode='middle'
autofocus-windows=false
enable-titlebar-actions=false
extend-left-box=false
greyscale-tray-icons=true
hide-activities-button='never'
hide-aggregate-menu-arrow=true
hide-app-menu-arrow=true
hide-app-menu-icon=false
hide-dropdown-arrows=true
hide-window-titlebars='always'
notifications-position='center'
reduce-panel-spacing=true
restrict-to-primary-screen=false
show-desktop-name=false
show-legacy-tray=false
show-window-buttons='never'
show-window-title='both'
window-buttons-placement='last'
window-buttons-theme='osx-arc'

[org/gnome/shell/extensions/user-theme]
name='dracula'

[org/gnome/system/location]
enabled=false

[org/gnome/terminal/legacy/keybindings]
full-screen='F11'
new-tab='<Primary>t'
select-all='<Primary>a'
toggle-menubar='disabled'

[org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9]
background-color='rgb(0,0,0)'
background-transparency-percent=100
bold-color-same-as-fg=true
bold-is-bright=false
cursor-colors-set=true
font='Fira Code 12'
use-theme-colors=true
use-theme-transparency=true
use-transparent-background=false

[org/gtk/settings/color-chooser]
custom-colors=[(0.93333333333333335, 0.93333333333333335, 0.93333333333333335, 1.0)]
selected-color=(true, 0.0, 0.0, 0.0, 1.0)
