version: '3.3'
services:
    rstudio:
        image: rstudio
        ports:
            - "8787:8787"
        environment:
            - DISABLE_AUTH=true
        volumes:
            - /mnt/c853ed2a-d0cf-4f28-96bf-f49b1dabdba9:/home/rstudio
